# Generated by Django 4.1 on 2022-09-07 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_user_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOfUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(verbose_name='created')),
                ('updated_at', models.DateTimeField(verbose_name='updated')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feed.typeofservice'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feed.status'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_of_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feed.typeofproduct'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feed.statusofusers'),
        ),
    ]
