# Generated by Django 4.1 on 2022-09-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_statusofusers_alter_service_service_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(verbose_name='created')),
                ('updated_at', models.DateTimeField(verbose_name='updated')),
            ],
        ),
    ]
