# Generated by Django 4.1 on 2022-09-09 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_item_type_of_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Client',
            new_name='client',
        ),
    ]
