# Generated by Django 4.1 on 2022-09-09 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_rename_client_service_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 0, 35, 43, 849989), verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 0, 35, 43, 849989), verbose_name='updated'),
        ),
    ]
