# Generated by Django 4.1 on 2022-09-20 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_remove_level_created_at_remove_level_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='name',
            new_name='level_name',
        ),
        migrations.RenameField(
            model_name='statusofusers',
            old_name='name',
            new_name='status_of_users_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='level',
            new_name='level_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='status_of_users_name',
        ),
    ]
