# Generated by Django 4.1 on 2022-09-21 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_rename_name_level_level_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusofusers',
            name='status_of_users_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level_name',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='feed.level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_of_users_name',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='feed.statusofusers'),
        ),
    ]
