# Generated by Django 4.1 on 2022-09-22 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_alter_statusofusers_status_of_users_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='clientcomment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clientcomment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='itemdetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='itemdetail',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='servicecomment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='servicecomment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='typeofitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='typeofitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='typeofproduct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='typeofproduct',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='typeofservice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='typeofservice',
            name='updated_at',
        ),
    ]
