# Generated by Django 4.1 on 2022-10-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_remove_client_created_at_remove_client_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
