# Generated by Django 4.1 on 2022-10-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_service_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
