# Generated by Django 4.1 on 2022-10-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_alter_client_created_alter_client_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='service',
            name='service_reference',
            field=models.CharField(default=666, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='adress',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
