# Generated by Django 4.1 on 2022-10-14 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0017_remove_level_reference_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status_of_users_name',
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='StatusOfUsers',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
