# Generated by Django 4.1 on 2022-10-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_remove_user_level_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='accesories',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
